apiVersion: v1
items:
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
      name: aws-secrets-manager
    spec:
      provider:
        aws:
          region: us-east-1
          service: SecretsManager
          sessionTagsPolicy: None
kind: List
metadata: {}
