apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
  - ../../base/core/namespaces/postgres/
  - base/
labels:
  - includeSelectors: true
    pairs:
      massopen.cloud/bundle: postgres
