apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: keycloak-certificate
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: keycloak-service
  dnsNames:
    - keycloak-service
    - keycloak-service.keycloak.svc
    - keycloak-service.keycloak.svc.cluster.local
