apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - namespace.yaml
  - https://github.com/keycloak/keycloak-k8s-resources//kubernetes?ref=26.7.5
  - keycloak.yaml
  - keycloak-certificate.yaml
  - postgres-pguser-keycloak.yaml
